### ISSUE TITLE
better missing ASDs communication in refgenie compare  

### ISSUE THREAD

**Issue by stolarczyk** [refgenie/refgenconf#118]
This is the error message that refgenie compare yields when such "incomplete" genome is used

```
refgenconf.exceptions.MissingSeekKeyError: Asset incomplete. No seek keys are defined for '94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta:default'. Build or pull the asset again.
```

need to make this more digestible, only the last part hints at what is the solution

**Comment by stolarczyk** [comment]
this is what it says now:
```
refgenconf.exceptions.MissingSeekKeyError: Failed to compare genomes; fasta asset for 'hg38' genome is incomplete, which probably means that it was pulled from the server as a parent of another asset. Build or pull 'hg38/fasta' specifically to use it for comparison.
```

**Comment by nsheff** [comment]
I think the speculative reason is not really necessary... what do you think of this instead?

> refgenconf.exceptions.MissingSeekKeyError: Failed to compare genomes. You must build or pull 'hg38/fasta'  before comparing genome 'hg38'.

**Comment by stolarczyk** [comment]
ok
