### ISSUE TITLE
seek remote assets return value

### ISSUE THREAD

**Issue by stolarczyk** [refgenie/refgenconf#121]
once we [include unarchived assets on the server](https://github.com/refgenie/refgenieserver/issues/100), we will be able to add `RefGenConf.seekr` method, which will point to a remote location of a file that `seek_key` points to. Two questions:

1. What about `seek_keys` that point to nonexistent files? Introduced in bowtie2_index recipe, e.g. [`hg38/bowtie2_index`](http://refgenomes.databio.org/v3/assets/splash/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/bowtie2_index?tag=default)
2. Do we want to return the refgenieserver endpoint path? or the S3 location of the file that the endpoint redirects to? or the `S3Uri`? or all are an option and one of them is the default? 
 - `http://refgenomes.databio.org/v3/...` 
 - `http://awspds.refgenie.databio.org/refgenomes.databio.org/....`
 - `s3://awspds.refgenie.databio.org/refgenomes.databio.org/...`

**Comment by nsheff** [comment]
```
refgenie seek t7/bowtie2_index
/home/nsheff/code/refgenie_sandbox/alias/t7/bowtie2_index/default/t7
```

I think you'd point to:

http://awspds.refgenie.databio.org/refgenomes.databio.org/t7/bowtie2_index/default/t7

so it wouldn't point to a file, if the seek key doesn't point to a file.

2. I'd give an option to return either the S3 URL location, or the S3Uri. Maybe it's `refgenie seekr` and `refgenie seekr -s3`.

Or, this could just be `refgenie seek` if there's a config mode like `mode: remote`? that turns all `seeks` into remote URLs?
