### ISSUE TITLE
alias links to log files appear to be wrong

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenconf#122]
The refgenie `alias` dir uses symlinks to point to the `data` dir. These links are correct on our main rivanna genomes directory:
![image](https://user-images.githubusercontent.com/5271009/112311992-afe84400-8c7c-11eb-8f11-f21edc372835.png)

But when I build for a new server, I see this:

![image](https://user-images.githubusercontent.com/5271009/112312197-ed4cd180-8c7c-11eb-847d-7a46c720f77d.png)

The links point to the wrong level, I think they need 5 `../` levels rather than 4.

**Comment by stolarczyk** [comment]
did you try running some tests again? The assets I built for rg.databio.org a couple of days ago have functional symlinks: `$PROJECT/deploy/rg.databio.org/genomes/alias/hg38/fasta/default`.
Is it possible that this is somehow specific to your setup?

**Comment by stolarczyk** [comment]
ah ok, I see the issue. It's about files in `_refgenie_build` _only_
