### ISSUE TITLE
tags in `RefGenConf.populate`?

### ISSUE THREAD

**Issue by stolarczyk** [refgenie/refgenconf#125]
It appears that `RefGenConf.populate` does not respect tags. Note the `:test` string appended to the output path below.
```python
In [1]: from refgenconf import RefGenConf

In [2]: rgc = RefGenConf("g.yml")

In [3]: rgc.populate(glob="refgenie://rCRSd/fasta:test")
Out[3]: '/Users/mstolarczyk/Desktop/testing/refgenie/alias/rCRSd/fasta/default/rCRSd.fa:test'
```

also: https://github.com/refgenie/refgenconf/runs/2270085297#step:8:59

Is that intentional?

Changing the regex from `"refgenie://([A-Za-z0-9_/\.]+)?"` to `"refgenie://([A-Za-z0-9_/\.\:]+)?"` solves the issue.

**Comment by nsheff** [comment]
Not intentionally -- I just didn't test it with tagged assets. So, I think your change is probably correct

**Comment by stolarczyk** [comment]
ok, that's what I thought. Just wanted to make sure it's not sth related to nfcore usages etc.
