### ISSUE TITLE
A list of seek keys

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenconf#128]
I couldn't find it in the docs -- given a genome and asset, can I get a list of seek keys?

Really, what I want is to do something like:

```
seek_keys = rgc.get_seek_path_dict("hg38")
```

and then refer to the paths, now in dict form, like:
```
seek_keys.fasta.chrom_sizes
seek_keys.bowtie2_index.default
```

I can create something like this for default seek keys very easily like this:

```
ret = {}

g = "t7"
for a in rgc.list_assets_by_genome(g):
	ret[a] = rgc.seek(g, a, "default")
```

But I need this for all seek keys.

**Comment by stolarczyk** [comment]
Just added a method that will help: https://github.com/refgenie/refgenconf/pull/129/commits/3c8945eecc04ad6e25ece75844f15b7951d195ca

**Comment by nsheff** [comment]
awesome, that's all I needed!
